name: CI

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: cd docker && docker build -t caverne-aux-jeux -f docker/Dockerfile .
      - name: Run main.py (test run)
        run: |
          cd docker && docker run --rm caverne-aux-jeux python app/main.py --help || true  # Replace with a real test if available

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: cd docker && docker build -t caverne-aux-jeux .
      - name: Run Docker container (test)
        run: cd docker && docker run --rm caverne-aux-jeux --help || true  # Replace with a real test if available

  build-linux:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: cd docker && docker build -t caverne-aux-jeux -f docker/Dockerfile .
      - name: Build executable (Linux)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace caverne-aux-jeux \
            make build-linux
      - name: Upload Linux executable
        uses: actions/upload-artifact@v3
        with:
          name: caverne-aux-jeux-linux
          path: dist/main

  build-windows:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Build executable (Windows)
        run: make build-windows
      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: caverne-aux-jeux-windows
          path: dist/main.exe

  release-artifacts:
    if: github.event_name == 'release'
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: caverne-aux-jeux-linux
          path: ./linux
      - uses: actions/download-artifact@v3
        with:
          name: caverne-aux-jeux-windows
          path: ./windows
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./linux/main
            ./windows/main.exe
          path: ./linux
      - uses: actions/download-artifact@v3
        with:
          name: caverne-aux-jeux-windows
          path: ./windows
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./linux/main
            ./windows/main.exe
      - uses: actions/download-artifact@v3
        with:
          name: caverne-aux-jeux-windows
          path: ./windows
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./linux/main
            ./windows/main.exe
